name: 'Balena versionist'
description: 'Opinionated versioning by balena'
inputs:
  github_email:
    description: 'GitHub email to use for commits.'
    required: true
  github_username:
    description: 'GitHub username to use for commits.'
    required: true
  github_token:
    description: 'GitHub token to use for commits. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
