name: 'Balena versionist'
description: 'Versioning done easy.'
inputs:
  github_email:
    description: 'GitHub email. Can be passed in using $\{{ secrets.GITHUB_EMAIL }}'
    required: true
  github_username:
    description: 'GitHub username. Can be passed in using $\{{ secrets.GITHUB_USERNAME }}'
    required: true
  github_token:
    description: 'Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
