name: Run balena versionist
on:
  push:
    branches:
      - master

jobs:
  test-job:
     runs-on: ubuntu-latest
     steps: 
     - uses: actions/checkout@v1
     - name: balena-versionist
       uses: ./
       with:
        github_email: 'tomasmigone@gmail.com'
        github_username: 'Tomás Migone'
        github_token: ${{ secrets.GITHUB_TOKEN }}