name: Run versionist action
on:
  push:
    branches:
      - master

jobs:

  versionist:
    if: "!contains(github.event.head_commit.author.name, 'versionist')"
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.versionist.outputs.version }}
      updated: ${{ steps.versionist.outputs.updated }}
    steps:
    - name: Checkout project code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Run balena-versionist
      id: versionist
      uses: ./
      with:
        github_email: 'tmigone.versionist@gmail.com'
        github_username: 'versionist'
        github_token: ${{ secrets.GH_VERSIONIST_TOKEN }}

  output:
    needs: versionist
    if: needs.versionist.outputs.updated == 'false'
    runs-on: ubuntu-latest
    name: A job to echo versionist's outputs
    steps:
    - name: Echo version number
      run: echo "Version is ${{ needs.versionist.outputs.version }}"
    - name: Echo updated
      run: echo "Updated is ${{ needs.versionist.outputs.updated }}"