name: Run versionist action
on:
  push:
    branches:
      - master

jobs:
  versionist:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Run versionist
      uses: ./
      with:
        github_email: 'tomasmigone@gmail.com'
        github_username: 'Tomás Migone'
        github_token: ${{ secrets.GITHUB_TOKEN }}